export const DIRECTIONS = {
  'n': 'direction.n',
  'nne': 'direction.nne',
  'ne': 'direction.ne',
  'ene': 'direction.ene',
  'e': 'direction.e',
  'ese': 'direction.ese',
  'se': 'direction.se',
  'sse': 'direction.sse',
  's': 'direction.s',
  'ssw': 'direction.ssw',
  'sw': 'direction.sw',
  'wsw': 'direction.wsw',
  'w': 'direction.w',
  'wnw': 'direction.wnw',
  'nw': 'direction.nw',
  'nnw': 'direction.nnw'
};

export const DIRECTIONS_BEARINGS: Record<string, number> = {
  'n': 0,
  'nne': 22.5,
  'ne': 45,
  'ene': 67.5,
  'e': 90,
  'ese': 112.5,
  'se': 135,
  'sse': 157.5,
  's': 180,
  'ssw': 202.5,
  'sw': 225,
  'wsw': 247.5,
  'w': 270,
  'wnw': 292.5,
  'nw': 315,
  'nnw': 337.5,
};
